### ISSUE TITLE
请问一下rtsp格式问题

### ISSUE THREAD

**Issue by lampsonSong** [darkise/mpp_rtsp_player#1]
您好，我用您的程序已经编译通过了，但是在拉rtsp流时发现如果有用户名密码不能正确识别格式，请问这个该怎么解决？谢谢。
- 比如一个rtsp流ip是192.168.1.10，用户名和密码分别是admin, 1234， 我们之前用的url就是rtsp://admin:1234@192.168.1.10，现在不太明白怎么写这个格式了，望指教，多谢

**Comment by darkise** [comment]
RTSP的代码是我自己写的，并没有支持用户名密码方式。抱歉。

**Comment by lampsonSong** [comment]
> RTSP的代码是我自己写的，并没有支持用户名密码方式。抱歉。

您客气，后来我用FFMPEG拉流了，把AVPacket里的数据再copy出来，喂到解码器里，可以成功解码了。感谢您的工作。
